package GUI;

import javax.swing.JLabel;
import Logica.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Proyecto SO - Trimestre 1718-2
 *Hecho por César Salazar y Loredana de Miro 
 */
public class InterfazFabrica extends javax.swing.JFrame 
{

    Fabrica fabrica_robots;

    public InterfazFabrica() throws IOException
    {
        initComponents();
        this.setLocationRelativeTo(null);
        fabrica_robots= new Fabrica (this.nroDiasDespacho, this.cantidadCabezas, this.cantidadCuerpos, this.cantidadExtremidades, this.cantidadProdCab, this.cantidadProdCuerpo, this.cantidadProdExtrem, this.cantidadEnsambladores, this.cantidadRobots, this.estadoGerente, this.estadoCrono, this.nroDias);
        fabrica_robots.Inicializar_ArrayLists();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        extremidades = new javax.swing.JLabel();
        cuerpo = new javax.swing.JLabel();
        cantRobotsProducidos = new javax.swing.JLabel();
        diasDespacho = new javax.swing.JLabel();
        hombresMecanicos = new javax.swing.JLabel();
        cabezaRobot = new javax.swing.JLabel();
        estatusGerente = new javax.swing.JLabel();
        estatusCronometrador = new javax.swing.JLabel();
        Pausar = new javax.swing.JButton();
        Reanudar = new javax.swing.JButton();
        cabezaDatos = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantidadCabezas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cantidadProdCab = new javax.swing.JLabel();
        contratarProdCab = new javax.swing.JButton();
        despedirProdCab = new javax.swing.JButton();
        cuerpoDatos = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cantidadCuerpos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cantidadProdCuerpo = new javax.swing.JLabel();
        contratarProdCuerpos = new javax.swing.JButton();
        despedirProdCuerpos = new javax.swing.JButton();
        extremidadesDatos = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cantidadExtremidades = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cantidadProdExtrem = new javax.swing.JLabel();
        contratarProdExtrem = new javax.swing.JButton();
        despedirProdExtrem = new javax.swing.JButton();
        ensambladores = new javax.swing.JLabel();
        contratarEnsamblador = new javax.swing.JButton();
        despedirEnsamblador = new javax.swing.JButton();
        cantidadEnsambladores = new javax.swing.JLabel();
        robotimg = new javax.swing.JLabel();
        cantidadRobots = new javax.swing.JLabel();
        nroDiasDespacho = new javax.swing.JLabel();
        estadoGerente = new javax.swing.JLabel();
        estadoCrono = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        diasTranscurridos = new javax.swing.JLabel();
        nroDias = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        extremidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        extremidades.setForeground(new java.awt.Color(255, 255, 255));
        extremidades.setText("Extremidades");

        cuerpo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cuerpo.setForeground(new java.awt.Color(255, 255, 255));
        cuerpo.setText("Cuerpo");

        cantRobotsProducidos.setBackground(new java.awt.Color(255, 255, 204));
        cantRobotsProducidos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cantRobotsProducidos.setForeground(new java.awt.Color(255, 255, 255));
        cantRobotsProducidos.setText("Nro. Robots Producidos");

        diasDespacho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diasDespacho.setForeground(new java.awt.Color(255, 255, 255));
        diasDespacho.setText("Días que faltan para el despacho:");

        hombresMecanicos.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        hombresMecanicos.setForeground(new java.awt.Color(255, 255, 255));
        hombresMecanicos.setText("HOMBRES MECÁNICOS C.A.");

        cabezaRobot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cabezaRobot.setForeground(new java.awt.Color(255, 255, 255));
        cabezaRobot.setText("Cabeza");

        estatusGerente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estatusGerente.setForeground(new java.awt.Color(255, 255, 255));
        estatusGerente.setText("Estatus Gerente:");

        estatusCronometrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estatusCronometrador.setForeground(new java.awt.Color(255, 255, 255));
        estatusCronometrador.setText("Estatus Cronometrador:");

        Pausar.setText("Pausar");
        Pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PausarActionPerformed(evt);
            }
        });

        Reanudar.setText("Reanudar");
        Reanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReanudarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de cabezas producidas:");

        cantidadCabezas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadCabezas.setText("X");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/head.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cantidadCabezas)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cantidadCabezas)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cabezaDatos.addTab("Producción", jPanel2);

        jLabel3.setText("Cantidad de productores de cabezas:");

        cantidadProdCab.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadProdCab.setText("X");

        contratarProdCab.setText("contratar");
        contratarProdCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarProdCabActionPerformed(evt);
            }
        });

        despedirProdCab.setText("despedir");
        despedirProdCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirProdCabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cantidadProdCab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contratarProdCab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(despedirProdCab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadProdCab)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(contratarProdCab)
                        .addGap(18, 18, 18)
                        .addComponent(despedirProdCab)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        cabezaDatos.addTab("Productor", jPanel3);

        jLabel4.setText("Cantidad de cuerpos producidos:");

        cantidadCuerpos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadCuerpos.setText("X");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/body.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cantidadCuerpos)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cantidadCuerpos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuerpoDatos.addTab("Producción", jPanel4);

        jLabel7.setText("Cantidad de productores de cuerpos:");

        cantidadProdCuerpo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadProdCuerpo.setText("X");

        contratarProdCuerpos.setText("contratar");
        contratarProdCuerpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarProdCuerposActionPerformed(evt);
            }
        });

        despedirProdCuerpos.setText("despedir");
        despedirProdCuerpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirProdCuerposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cantidadProdCuerpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contratarProdCuerpos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despedirProdCuerpos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cantidadProdCuerpo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contratarProdCuerpos)
                        .addGap(18, 18, 18)
                        .addComponent(despedirProdCuerpos)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        cuerpoDatos.addTab("Productor", jPanel5);

        jLabel8.setText("Cantidad de extremidades producidas:");

        cantidadExtremidades.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadExtremidades.setText("X");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arms.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cantidadExtremidades)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cantidadExtremidades))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        extremidadesDatos.addTab("Producción", jPanel6);

        jLabel9.setText("Cantidad de productores de Extremidades:");

        cantidadProdExtrem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cantidadProdExtrem.setText("X");

        contratarProdExtrem.setText("contratar");
        contratarProdExtrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarProdExtremActionPerformed(evt);
            }
        });

        despedirProdExtrem.setText("despedir");
        despedirProdExtrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirProdExtremActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cantidadProdExtrem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contratarProdExtrem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despedirProdExtrem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cantidadProdExtrem))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contratarProdExtrem)
                        .addGap(18, 18, 18)
                        .addComponent(despedirProdExtrem)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        extremidadesDatos.addTab("Productor", jPanel7);

        ensambladores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ensambladores.setForeground(new java.awt.Color(255, 255, 255));
        ensambladores.setText("Cantidad de Ensambladores:");

        contratarEnsamblador.setText("contratar");
        contratarEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarEnsambladorActionPerformed(evt);
            }
        });

        despedirEnsamblador.setText("despedir");
        despedirEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirEnsambladorActionPerformed(evt);
            }
        });

        cantidadEnsambladores.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cantidadEnsambladores.setForeground(new java.awt.Color(255, 255, 255));
        cantidadEnsambladores.setText("X");

        robotimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/robot.jpg"))); // NOI18N

        cantidadRobots.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        cantidadRobots.setForeground(new java.awt.Color(255, 255, 255));
        cantidadRobots.setText("X");

        nroDiasDespacho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nroDiasDespacho.setForeground(new java.awt.Color(255, 255, 255));
        nroDiasDespacho.setText("X");

        estadoGerente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadoGerente.setForeground(new java.awt.Color(255, 255, 255));
        estadoGerente.setText("X");

        estadoCrono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadoCrono.setForeground(new java.awt.Color(255, 255, 255));
        estadoCrono.setText("X");

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        diasTranscurridos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diasTranscurridos.setForeground(new java.awt.Color(255, 255, 255));
        diasTranscurridos.setText("Días transcurridos:");

        nroDias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nroDias.setForeground(new java.awt.Color(255, 255, 255));
        nroDias.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(hombresMecanicos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cabezaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cabezaRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ensambladores))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(cantidadEnsambladores)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(despedirEnsamblador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contratarEnsamblador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(cuerpo)
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(extremidades, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantRobotsProducidos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(Pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estatusCronometrador)
                                .addGap(52, 52, 52)
                                .addComponent(estadoCrono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(estatusGerente)
                                        .addGap(68, 68, 68)
                                        .addComponent(estadoGerente))
                                    .addComponent(cuerpoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(extremidadesDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(cantidadRobots)
                                        .addGap(45, 45, 45)
                                        .addComponent(robotimg))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(nroDias))
                                            .addComponent(diasTranscurridos)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(diasDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nroDiasDespacho)))))))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hombresMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Iniciar)
                        .addComponent(Pausar)
                        .addComponent(Reanudar)))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extremidades)
                            .addComponent(cuerpo)
                            .addComponent(cabezaRobot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidadEnsambladores)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuerpoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cabezaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(extremidadesDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cantRobotsProducidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(robotimg)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(cantidadRobots)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ensambladores)
                            .addComponent(estatusGerente)
                            .addComponent(estadoGerente)
                            .addComponent(diasTranscurridos)
                            .addComponent(nroDias))
                        .addComponent(contratarEnsamblador)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(despedirEnsamblador))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(estatusCronometrador)
                                    .addComponent(estadoCrono)
                                    .addComponent(diasDespacho)
                                    .addComponent(nroDiasDespacho))))))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 1010, 450));

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondogrey.jpg"))); // NOI18N
        Fondo.setText("jLabel2");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratarEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarEnsambladorActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Contratar_Ensamblador();
    }//GEN-LAST:event_contratarEnsambladorActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void PausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PausarActionPerformed

        for (Object p_cab: fabrica_robots.Productor_cabeza) 
        {
          ((Productor)p_cab).setParar(true); 
        }
        for (Object p_cue: fabrica_robots.Productor_cuerpo) 
        {
          ((Productor)p_cue).setParar(true); 
        }
        for (Object p_ext: fabrica_robots.Productor_extremidad) 
        {
          ((Productor)p_ext).setParar(true); 
        }
        for (Object ens: fabrica_robots.Ensambladores) 
        {
          ((Productor)ens).setParar(true); 
        }
        
    }//GEN-LAST:event_PausarActionPerformed

    private void contratarProdCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarProdCabActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Contratar_Prod_Cabeza();
    }//GEN-LAST:event_contratarProdCabActionPerformed

    private void contratarProdCuerposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarProdCuerposActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Contratar_Prod_Cuerpo();
    }//GEN-LAST:event_contratarProdCuerposActionPerformed

    private void contratarProdExtremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarProdExtremActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Contratar_Prod_Extremidad();
    }//GEN-LAST:event_contratarProdExtremActionPerformed

    private void despedirProdCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirProdCabActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Despedir_Prod_Cabeza();
    }//GEN-LAST:event_despedirProdCabActionPerformed

    private void despedirProdCuerposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirProdCuerposActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Despedir_Prod_Cuerpo();
    }//GEN-LAST:event_despedirProdCuerposActionPerformed

    private void despedirProdExtremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirProdExtremActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Despedir_Prod_Extremidad();
    }//GEN-LAST:event_despedirProdExtremActionPerformed

    private void despedirEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirEnsambladorActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Despedir_Ensamblador();
    }//GEN-LAST:event_despedirEnsambladorActionPerformed

    private void ReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReanudarActionPerformed
        for (Object p_cab: fabrica_robots.Productor_cabeza) 
        {
          ((Productor)p_cab).getDetener().release(); 
        }
        for (Object p_cue: fabrica_robots.Productor_cuerpo) 
        {
          ((Productor)p_cue).getDetener().release(); 
        }
        for (Object p_ext: fabrica_robots.Productor_extremidad) 
        {
          ((Productor)p_ext).getDetener().release(); 
        }
        for (Object ens: fabrica_robots.Ensambladores) 
        {
          ((Productor)ens).getDetener().release(); 
        }         
    }//GEN-LAST:event_ReanudarActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        fabrica_robots.Producir_Ensamblar();
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                try 
                {
                    new InterfazFabrica().setVisible(true);
                } 
                catch (IOException ex) 
                {
                    Logger.getLogger(InterfazFabrica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Pausar;
    private javax.swing.JButton Reanudar;
    private javax.swing.JTabbedPane cabezaDatos;
    private javax.swing.JLabel cabezaRobot;
    private javax.swing.JLabel cantRobotsProducidos;
    private javax.swing.JLabel cantidadCabezas;
    private javax.swing.JLabel cantidadCuerpos;
    private javax.swing.JLabel cantidadEnsambladores;
    private javax.swing.JLabel cantidadExtremidades;
    private javax.swing.JLabel cantidadProdCab;
    private javax.swing.JLabel cantidadProdCuerpo;
    private javax.swing.JLabel cantidadProdExtrem;
    private javax.swing.JLabel cantidadRobots;
    private javax.swing.JButton contratarEnsamblador;
    private javax.swing.JButton contratarProdCab;
    private javax.swing.JButton contratarProdCuerpos;
    private javax.swing.JButton contratarProdExtrem;
    private javax.swing.JLabel cuerpo;
    private javax.swing.JTabbedPane cuerpoDatos;
    private javax.swing.JButton despedirEnsamblador;
    private javax.swing.JButton despedirProdCab;
    private javax.swing.JButton despedirProdCuerpos;
    private javax.swing.JButton despedirProdExtrem;
    private javax.swing.JLabel diasDespacho;
    private javax.swing.JLabel diasTranscurridos;
    private javax.swing.JLabel ensambladores;
    private javax.swing.JLabel estadoCrono;
    private javax.swing.JLabel estadoGerente;
    private javax.swing.JLabel estatusCronometrador;
    private javax.swing.JLabel estatusGerente;
    private javax.swing.JLabel extremidades;
    private javax.swing.JTabbedPane extremidadesDatos;
    private javax.swing.JLabel hombresMecanicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel nroDias;
    private javax.swing.JLabel nroDiasDespacho;
    private javax.swing.JLabel robotimg;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
